### ISSUE TITLE
Label on github should include pi4 

### ISSUE THREAD

**Issue by knitzsche** [snapcore/pi-gadget#32]
Currently it says: Universal pi (pi2,pi3,cm3) gadget snap for core18

But it is the ucore 18 pi4 gadget too, as I understand it.

**Comment by xnox** [comment]
Also README.md need adjustment.

I think i adjusted the title now.

**Comment by knitzsche** [comment]
thanks!

**Comment by anonymouse64** [comment]
The title should also specify that this gadget is for uc20 too

**Comment by anonymouse64** [comment]
@Meulengracht I think this bug is just about editing the repo itself, not in the README, i.e. the "About" section on the right of this webpage:

![image](https://user-images.githubusercontent.com/6006573/142663082-b0d0828a-850d-48cc-8d37-2fbb4955b30f.png)

I think any repo admin should have the power to edit that, for repos I am an admin on there is a little gear button next to it that I can use to edit the description

**Comment by sil2100** [comment]
I updated the description, thanks!
