### ISSUE TITLE
classic pi-gadget should be published as a snap

### ISSUE THREAD

**Issue by xnox** [snapcore/pi-gadget#50]
classic pi-gadget should be published as a snap in the store (maybe on a separate classic track, which might be the same as regular gadget, or not. May need to be build on the right target series however.

that way livecd-rootfs/ubuntu-image can stop cloning this git repository, and instead just download the gadget and use it.

**Comment by vorlonofportland** [comment]
On Wed, Aug 19, 2020 at 04:48:06AM -0700, Dimitri John Ledkov wrote:

> classic pi-gadget should be published as a snap in the store (maybe on a
> separate classic track, which might be the same as regular gadget, or not. 
> May need to be build on the right target series however.

> that way livecd-rootfs/ubuntu-image can stop cloning this git repository,
> and instead just download the gadget and use it.

Nack.  There's no value in publishing this as a snap instead of as a git
tree, it's an indirection that only complicates things.  The design for
classic images is to use a gadget tree, not a gadget snap.

-- 
Steve Langasek                   Give me a lever long enough and a Free OS
Debian Developer                   to set it on, and I can move the world.
Ubuntu Developer                                   https://www.debian.org/
slangasek@ubuntu.com                                     vorlon@debian.org
