### ISSUE TITLE
DTBS changes in stable channel

### ISSUE THREAD

**Issue by avazar** [snapcore/pi-gadget#78]
Hello!

It's currently [impossible to build UC18 image](https://forum.snapcraft.io/t/building-custom-image-fails-cannot-find-dtbs-in-kernel-info/25729) using the pi gadget from the stable channel due to [Changes in pi/pi-kernel DTB handling](https://forum.snapcraft.io/t/changes-in-pi-pi-kernel-dtb-handling/24369).

The required changes are already implemented and are available in the edge channel in the snapcraft store.
Is it possible to move them to the stable channel? When is it planned?

**Comment by sil2100** [comment]
Hello avazar! This is interesting - the stable pi gadget should have all the required DTB changes already. AFAICT, the only thing that the pi UC18 edge snap has that stable doesn't is a MIR-related change to the cmdline.

If you check the history, the DTB-related commits got merged on the 29 Apr and then built and uploaded to the store the same day and on the 7th for armhf (because there was a follow up fix) - both those revisions are 98 and 100. I checked the git revs and they seem to be built from the correct code. Both those revisions are in stable since a long time.

Is this still a problem? It shouldn't require the edge snap at all, we should have all we need in stable now.

**Comment by avazar** [comment]
Thank you for the answer! 
If the changes were uploaded on the 28th of April, that's really strange that this issue appeared in July and August. 

However, I've tried to build the image again today - and everything was OK. 
So, I guess, everything is OK and this can be closed.
